# n dim start state.
float64[] start

# n dim initial velocity. Timestep value ignored
float64[] initial_velocity

# n dim goal state.
float64[] goal

# n dim obstacle position (initial position in case of moving obstacle)
float64[] obs_pos

#n dim obstacle velocity (should be set to zero for static obstacles)
float64[] obs_vel

# Speed of replay.
float64 tau

# time resolution for numerical intergration
float64 dt

# mode of potential field for DMP
string mode

---

# the generated plan
Plan generated_plan